
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"fz-updateSpring3","number":63,"title":"Fz update spring3","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/63"},{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"fz-colorChange","number":60,"title":"Sections Table Base UI improvement","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/60"},{"author":{"id":"U_kgDOBqpQ0A","is_bot":false,"login":"monicatrinh1","name":"Monica Trinh"},"headRefName":"Monica-Bug","number":59,"title":"fix bug where you can add incorrect class to schedule","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/59"},{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-PersonalSchedule-OptDesc","number":54,"title":"Make PersonalSchedule Form Description Optional","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/54"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-LoadGradeData-new","number":50,"title":"Lm load grade data new","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/50"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-LoadGradeData","number":35,"title":"Load grade data in admins page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/35"}]
