
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"fz-endQtrDefault","number":34,"title":"change default quarter to end qtr","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-show-h2console-link","number":30,"title":"Lm show h2console link","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/30"},{"author":{"id":"U_kgDOBXjsvQ","is_bot":false,"login":"ericknee","name":""},"headRefName":"bug-coursesSearchButton","number":27,"title":"EN - Fixed Bug: Made \"UCSB Courses Search\" button appear clearly as button","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/27"},{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"newRemoveCourseUI","number":25,"title":"Remove Courses bar to improve UI","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/pull/25"}]
